IMAGE_NAME=tts-practica
CONTAINER_NAME=tts-container

build:
	docker build -t $(IMAGE_NAME) .

run:
	docker run -it --name $(CONTAINER_NAME) -v "$$(pwd)":/app $(IMAGE_NAME)

clean:
	docker rm -f $(CONTAINER_NAME) || true
	docker rmi -f $(IMAGE_NAME) || true
